apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: kaniko-2
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout

      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Set up Docker Hub registrydd
        kind: deploy
        with:
          registry: https://index.docker.io/v1/
          username: karakurty
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: kaniko-build
        uses: cloudbees-io/kaniko/.cloudbees/testing@CBP-16854
        name: Build a container image with Kaniko
        with:
          destination: index.docker.io/karakurty/hello-world-docker:VFEZLER-${{cloudbees.version}}, index.docker.io/karakurty/hello-world-docker:VFEZLER-latest
          labels: app=cbp

      - uses: docker://golang:1.20.3-alpine3.17
        name: echo
        shell: sh
        run: |
          echo "artifactIds value: ${{ steps.kaniko-build.outputs.artifactIds }}"
          echo "single artifact ID per dynamically generated destination '${{ env.DESTINATION }}': ${{ fromJSON(steps.kaniko-build.outputs.artifactIds)[env.DESTINATION] }}"
          echo "single artifact ID per static destination 'index.docker.io/karakurty/hello-world-docker:VFEZLER-latest': ${{ fromJSON(steps.kaniko-build.outputs.artifactIds)['index.docker.io/karakurty/hello-world-docker:VFEZLER-latest'] }}"
        env:
          DESTINATION:  "index.docker.io/karakurty/hello-world-docker:VFEZLER-${{ cloudbees.version }}"
