apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: kaniko-2
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout

      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Set up Docker Hub registrydd
        kind: deploy
        with:
          registry: https://index.docker.io/v1/
          username: karakurty
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: kaniko
        uses: cloudbees-io/kaniko/.cloudbees/testing@CBP-16854
        name: kaniko
        with:
          destination: index.docker.io/karakurty/hello-world-docker:VFEZLER-${{cloudbees.version}}
          labels: app=cbp

      - uses: docker://golang:1.20.3-alpine3.17
        name: echo
        shell: sh
        run: |
          echo "hello world version ${{ cloudbees.version }}"
          echo "toJSON(steps.kaniko.outputs): ${{ toJSON(steps.kaniko.outputs) }}"
          echo "steps.kaniko.outputs.artifactIds: ${{ steps.kaniko.outputs.artifactIds }}"
          echo "single artifactId: ${{ fromJSON(steps.kaniko.outputs.artifactIds)["index.docker.io/karakurty/hello-world-docker:VFEZLER-${{cloudbees.version}}"] }}"
